# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='events', to='log_app.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='log_app.User')),
            ],
        ),
    ]
